export interface TransaksiAset {
  id: string
  no_po: string
  nama_aset: string
  kategori: string
  pemohon: string
  divisi: string
  tgl_pengajuan: string
  qty: number
  satuan: string
  nilai_total: string
  prioritas: "Tinggi" | "Sedang" | "Rendah"
  status: "Disetujui" | "Menunggu" | "Ditolak" | "Draft"
}

export const dummyTransaksi: TransaksiAset[] = [
  {
    id: "1",
    no_po: "PO-2025-001",
    nama_aset: "Laptop Dell Latitude 5540",
    kategori: "IT & Komputer",
    pemohon: "Andi Saputra",
    divisi: "Divisi IT",
    tgl_pengajuan: "03 Jan 2025",
    qty: 5,
    satuan: "unit",
    nilai_total: "Rp 42.500.000",
    prioritas: "Tinggi",
    status: "Disetujui",
  },
  {
    id: "2",
    no_po: "PO-2025-002",
    nama_aset: "Kursi Ergonomis NeueChair Pro",
    kategori: "Furnitur",
    pemohon: "Rina Dewi",
    divisi: "HR & GA",
    tgl_pengajuan: "05 Jan 2025",
    qty: 20,
    satuan: "unit",
    nilai_total: "Rp 60.000.000",
    prioritas: "Sedang",
    status: "Disetujui",
  },
  {
    id: "3",
    no_po: "PO-2025-003",
    nama_aset: "Printer Laser HP LaserJet Pro M404",
    kategori: "IT & Komputer",
    pemohon: "Budi Hartono",
    divisi: "Keuangan",
    tgl_pengajuan: "08 Jan 2025",
    qty: 3,
    satuan: "unit",
    nilai_total: "Rp 9.750.000",
    prioritas: "Rendah",
    status: "Menunggu",
  },
  {
    id: "4",
    no_po: "PO-2025-004",
    nama_aset: "Toyota Avanza 1.5 G CVT",
    kategori: "Kendaraan",
    pemohon: "Sari Utami",
    divisi: "Direksi",
    tgl_pengajuan: "10 Jan 2025",
    qty: 1,
    satuan: "unit",
    nilai_total: "Rp 230.000.000",
    prioritas: "Tinggi",
    status: "Disetujui",
  },
  {
    id: "5",
    no_po: "PO-2025-005",
    nama_aset: "UPS Cyberpower CP1000AVRLCD",
    kategori: "IT & Komputer",
    pemohon: "Dodi Prasetyo",
    divisi: "IT & Infrastruktur",
    tgl_pengajuan: "12 Jan 2025",
    qty: 10,
    satuan: "unit",
    nilai_total: "Rp 15.000.000",
    prioritas: "Sedang",
    status: "Ditolak",
  },
  {
    id: "6",
    no_po: "PO-2025-006",
    nama_aset: "Meja Kerja Standing Desk Adjustable",
    kategori: "Furnitur",
    pemohon: "Maya Kusuma",
    divisi: "HR & GA",
    tgl_pengajuan: "15 Jan 2025",
    qty: 8,
    satuan: "unit",
    nilai_total: "Rp 24.000.000",
    prioritas: "Rendah",
    status: "Draft",
  },
  {
    id: "7",
    no_po: "PO-2025-007",
    nama_aset: "Server Dell PowerEdge R750",
    kategori: "IT & Komputer",
    pemohon: "Hendra Wijaya",
    divisi: "Divisi IT",
    tgl_pengajuan: "17 Jan 2025",
    qty: 2,
    satuan: "unit",
    nilai_total: "Rp 180.000.000",
    prioritas: "Tinggi",
    status: "Menunggu",
  },
  {
    id: "8",
    no_po: "PO-2025-008",
    nama_aset: "AC Split Daikin 2 PK Inverter",
    kategori: "Elektronik",
    pemohon: "Fitri Handayani",
    divisi: "Umum",
    tgl_pengajuan: "20 Jan 2025",
    qty: 6,
    satuan: "unit",
    nilai_total: "Rp 36.000.000",
    prioritas: "Sedang",
    status: "Disetujui",
  },
  {
    id: "9",
    no_po: "PO-2025-009",
    nama_aset: "Proyektor Epson EB-X51",
    kategori: "Elektronik",
    pemohon: "Reza Firmansyah",
    divisi: "Marketing",
    tgl_pengajuan: "22 Jan 2025",
    qty: 3,
    satuan: "unit",
    nilai_total: "Rp 18.750.000",
    prioritas: "Rendah",
    status: "Ditolak",
  },
  {
    id: "10",
    no_po: "PO-2025-010",
    nama_aset: "CCTV Hikvision DS-2CD2143G2",
    kategori: "Keamanan",
    pemohon: "Lina Marlina",
    divisi: "Umum",
    tgl_pengajuan: "25 Jan 2025",
    qty: 12,
    satuan: "unit",
    nilai_total: "Rp 21.600.000",
    prioritas: "Sedang",
    status: "Menunggu",
  },
  {
    id: "11",
    no_po: "PO-2025-011",
    nama_aset: "Genset Perkins 50 kVA",
    kategori: "Infrastruktur",
    pemohon: "Agus Santoso",
    divisi: "Teknik",
    tgl_pengajuan: "28 Jan 2025",
    qty: 1,
    satuan: "unit",
    nilai_total: "Rp 125.000.000",
    prioritas: "Tinggi",
    status: "Draft",
  },
  {
    id: "12",
    no_po: "PO-2025-012",
    nama_aset: "iPhone 15 Pro Max 256GB",
    kategori: "IT & Komputer",
    pemohon: "Dewi Anggraini",
    divisi: "Direksi",
    tgl_pengajuan: "30 Jan 2025",
    qty: 4,
    satuan: "unit",
    nilai_total: "Rp 84.000.000",
    prioritas: "Tinggi",
    status: "Disetujui",
  },
]